version: '3'

services:
  app:
    build: ./app
    container_name: go_app
    command: go run /app/app.go
    volumes:
      - "./app:/app"
    ports:
      - "8080:8080"
    depends_on:
      - db
    # restart: always
  db:
    image: postgres:9.6-alpine
    container_name: go_db
    ports:
      - "543:5432"
    volumes:
      - db-data:/var/lib/postgresql
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    
volumes:
  db-data: